# Generated by Django 4.0.4 on 2022-05-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What category does this ticket belong to?', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('On-hold', 'On-hold')], default='Open', help_text='Current Status', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('summary', models.CharField(default='No Summary', help_text='Summarize Issue', max_length=100)),
                ('description', models.TextField(default='Needs Description', help_text='Describe your issue here:', max_length=500)),
                ('agent', models.ManyToManyField(help_text='Ticket Assignee', to='dashboard.agent')),
                ('category', models.ManyToManyField(help_text='Ticket Category', to='dashboard.category')),
                ('status', models.ManyToManyField(help_text='Enter ticket status', to='dashboard.status')),
            ],
        ),
    ]
