# Generated by Django 4.0.4 on 2022-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_agent_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
