# Generated by Django 4.0.4 on 2022-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinstance',
            name='summary',
            field=models.CharField(default='No Summary', help_text='Summarize Issue', max_length=100),
        ),
    ]
